services:
  postgres:
    image: postgres:18.0-alpine
    container_name: frame24-postgres
    environment:
      POSTGRES_USER: frame24
      POSTGRES_PASSWORD: frame24pass
      POSTGRES_DB: frame24
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - frame24-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U frame24" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: frame24-redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 50mb
      --maxmemory-policy allkeys-lru
      --maxmemory-samples 5
      --save ""
    volumes:
      - redis-data:/data
    networks:
      - frame24-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3

  maildev:
    image: maildev/maildev:2.2.1
    container_name: frame24-maildev
    ports:
      - "1025:1025" # SMTP
      - "1080:1080" # Web UI
    networks:
      - frame24-network
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:1080" ]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: frame24-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: frame24
      RABBITMQ_DEFAULT_PASS: frame24pass
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - frame24-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: frame24-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: frame24
      MINIO_ROOT_PASSWORD: frame24pass
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - frame24-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 3


  minio-setup:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z-cpuv1
    container_name: frame24-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - frame24-network
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 frame24 frame24pass;
      mc mb myminio/frame24 --ignore-existing;
      mc anonymous set download myminio/frame24;
      exit 0;
      "

#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: frame24-api
#    environment:
#      SPRING_PROFILES_ACTIVE: dev
#    ports:
#      - "8080:8080"
#    networks:
#      - frame24-network
#    depends_on:
#      postgres:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
#      minio:
#        condition: service_healthy
#      minio-setup:
#        condition: service_completed_successfully
#    healthcheck:
#      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8080/actuator/health || exit 1"]
#      interval: 15s
#      timeout: 10s
#      retries: 5
#      start_period: 40s

volumes:
  postgres_data:
  rabbitmq_data:
  redis-data:
  minio_data:

networks:
  frame24-network:
    driver: bridge
